version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: unless-stopped
    ports:
      - "222:222"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
    shm_size: "256m"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.students-epitech.ovh'
        gitlab_rails['gitlab_shell_ssh_port'] = 222
      GITLAB_ROOT_PASSWORD: foobarfoobar
      GITLAB_ROOT_EMAIL: antoine.le-guillou@epitech.eu

  gitlab-runner-1:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner

  gitlab-runner-2:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner

volumes:
  gitlab-runner-config: 